### ISSUE TITLE
入團申請! 我是 白蘭

### ISSUE THREAD

**Issue by WBhlietue** [MatchWorkshop/Join#10]
### 入團申請表

Discord ID: WBhlietue#4006

Git ID:

入團原因：WBhlietue

入團期望：

暱稱：白蘭

專長*：企劃/美術/程式/音樂/其他 程式

能參與製作時間：一天2-3小時

作品集：git/網站連結/作品名稱、擔任職位/參與部份 

https://play.google.com/store/apps/developer?id=HR+Games
https://github.com/WBhlietue

備註：[補充資料]

*專案或有能力要求，或需要回答考卷為進行職位能力評等，以確保相關人才就位和避免耽誤開發流程

.
.
.

程式：

1. 程式語言：c#， js

2. 曾使用的遊戲引掣：unity3d

3. 曾參與開發的專案、參與人數及開發所需時間#：15號派可雜貨屋，人數4， 時間~4個月

4. 自評：

#請標明有沒有發佈及按專案列出各項

（接考卷）

**Comment by jcs090218** [comment]
我有邀請你了, 請查收Email! Welcome on board! 😄
