### ISSUE TITLE
入團申請! 我是Toddy

### ISSUE THREAD

**Issue by Noplace0** [MatchWorkshop/Join#11]
### 入團申請表

Discord ID: Hang#5693

Git ID: Noplace0

入團原因： 製作19號專案

入團期望： 成為一個更好的人在遊戲設計/程式方面上

暱稱：Toddy

專長*：程式

能參與製作時間：週未/平日晚上

作品集：https://www.toddygame.com/

備註： 

*專案或有能力要求，或需要回答考卷為進行職位能力評等，以確保相關人才就位和避免耽誤開發流程

.
.
.

程式：

1. 程式語言：C#, Python, Java

2. 曾使用的遊戲引掣：Unity, Unreal, Rpg maker...

3. 曾參與開發的專案、參與人數及開發所需時間#： 
最近一個參與開發的專案是GMTK GameJam2020 上的 VOYAGER ，跟3名外國團隊合作，在48小時內完成的一個小遊戲。
其他多為學生作品，1-4個，大約開發一個月至兩個月。

4. 自評：在學中的遊戲程序員

#請標明有沒有發佈及按專案列出各項

（接考卷）

**Comment by jcs090218** [comment]
我有邀請你了, 請查收Email! Welcome on board! 😄
