### ISSUE TITLE
入團申請! 我是藍花龍

### ISSUE THREAD

**Issue by BlueFlowerDragon** [MatchWorkshop/Join#12]
### 入團申請表

Discord ID:BlueFlowerDragon#2468

Git ID:

入團原因：社團創建前跟到現在

入團期望：把遊戲必備的系統能夠開發並正常運作

暱稱：藍花龍(中文) BlueFlowerDragon(English)

專長*：程式、2D平台遊戲設計、簡易測試員

能參與製作時間：看專案和團隊成員狀況而定，每周上限10小時

作品集：
向日種子 https://home.gamer.com.tw/creationDetail.php?sn=4900720 程式full
Reconnect https://drive.google.com/file/d/1ag_Goltz2w8nKpSIoF5b3vPf6w-63hOM/view (遊戲載點) 程式 負責Menu、設定、存檔系統、計時器和Credits內容

備註：

.
.
.

程式：

1. 程式語言：C#

2. 曾使用的遊戲引掣：Unity

3. 曾參與開發的專案、參與人數及開發所需時間#：
向日種子：不含爬文時間18小時，4人開發(不含特別感謝名單)
Reconnect：8小時共6人開發

4. 自評：目前的話AI相關機制不熟實現功能

**Comment by jcs090218** [comment]
Invited, please check your email! Thanks!
