### ISSUE TITLE
入團申請! 我是Matsu Ken

### ISSUE THREAD

**Issue by wu40705** [MatchWorkshop/Join#13]
### 入團申請表

Discord ID: Matsu Ken#1087

Git ID: wu40705

入團原因：專案18

入團期望：累積作品與遊戲製作經驗

暱稱：MatsuKen

專長*：音樂音效

能參與製作時間：

作品集：https://www.youtube.com/channel/UCoBOsoikQAgdY4ElwC7Vl9g

備註：[補充資料]

專案18

.
.
.

程式：

1. 程式語言：

2. 曾使用的遊戲引掣：

3. 曾參與開發的專案、參與人數及開發所需時間#：

4. 自評：

**Comment by jcs090218** [comment]
已發出邀請了, 請察看信箱是否有收到邀請信(垃圾訊息也請一併查看). 

如果**成功**加入, 請把這個issue關閉! 感謝! ❤️
