### ISSUE TITLE
入團申請! 我是chonz

### ISSUE THREAD

**Issue by chonz369** [MatchWorkshop/Join#14]
入團申請表
Discord ID: Chonz#4795
Git ID: Zionch

入團原因/期望：想增加共同開發的經驗
暱稱：Chonz

專長*：程式
能參與製作時間： 每天大約1~2小時

備註：

程式：
程式語言：c#
曾使用的遊戲引掣：unity

曾參與開發的專案、參與人數及開發所需時間#：
1. SteelX (程式) :  https://www.youtube.com/watch?v=7s5RdfUIfxs&t=79s&ab_channel=Chonz
2. 晴天咖啡館 (程式)

自評：很菜

**Comment by jcs090218** [comment]
已發出邀請了, 請察看信箱是否有收到邀請信(垃圾訊息也請一併查看). 

如果**成功**加入, 請把這個issue關閉! 感謝! ❤️
