### ISSUE TITLE
入團申請! 我是 Kiloyd

### ISSUE THREAD

**Issue by Kiloyd** [MatchWorkshop/Join#15]
### 入團申請表

Discord ID: Kiloyd#9285

Git ID: 6846149

入團原因：想觀摩更多不同的專案開發

入團期望：學習並接觸不同的 workflow、改善自身協作的能力、探索遊戲程式開發中的各個面向

暱稱：Kevin

專長：程式

能參與製作時間： 一周約 5 小時

作品集：

[三知餘議題遊戲](https://reurl.cc/yenoKy) ─ 程式

[個人itch.io](https://kiloyd.itch.io/)

備註：[補充資料]

*專案或有能力要求，或需要回答考卷為進行職位能力評等，以確保相關人才就位和避免耽誤開發流程

.
.
.

程式：

1. 程式語言：C#、C++、Python

2. 曾使用的遊戲引掣：Unity (最熟悉且有做過專案)、UE4

3. 曾參與開發的專案、參與人數及開發所需時間：

[三知餘議題遊戲](https://reurl.cc/yenoKy) ─ 程式 ─ 已發布
參與人數：3 人
開發時長：半年 (3/16 受邀加入團隊，9/17 發布)

4. 自評：過去大多開發的程式都是一人，少有與人協作故程式碼的可閱讀性等協作方面的經驗欠缺，一方面開發成果也大多是 prototype 居多，對於完整的流程和各個眉角想要有更多了解

**Comment by jcs090218** [comment]
已發出邀請了, 請察看信箱是否有收到邀請信(垃圾訊息也請一併查看). 

如果**成功**加入, 請把這個issue關閉! 感謝! ❤️

**Comment by Kiloyd** [comment]
確認沒問題，感謝！
