### ISSUE TITLE
入團申請! 我是Tina

### ISSUE THREAD

**Issue by jane901201** [MatchWorkshop/Join#16]
### 入團申請表

Discord ID: 
Tina70245

Git ID: 
jane901201

入團原因：
程式學了這麼多年，覺得只靠書本跟網路資源還是會到一個極限，希望可以有可以詢問的人，讓自己可以在程式編寫這方面的能力可以更上一層樓，還有可以遇到與自己有相同興趣的人，一起製作出遊戲

入團期望：
希望自己可以在大三前有至少兩個完整的Unity作品，並想在明年4月前整理好以前跟入團後可以公開的作品後能夠嘗試去Foundesire跟雷亞之類的遊戲公司的實習看看，短期最大目標是可以直接進遊戲相關行業就業不繼續學業，但要是不行還是會乖乖念完大學。夢想是可以寫出能夠支撐3A遊戲的程式架構，不過以我目前的能力來看還有很長一段路要走......

暱稱：
林泉

專長*：企劃/美術/程式/音樂/其他
程式/劇本

能參與製作時間：
每天最多1.5小時，不過還是會根據要求進度去增加每天的製作時間，要是時限內空不出那麼多時間會直說

作品集：git/網站連結/作品名稱、擔任職位/參與部份
https://github.com/jane901201/SimplyShootingGame.git
程式
https://github.com/jane901201/Unreal.git
程式，只是用來練習設計模式的專案
https://github.com/rabbit99/FGJ2021.git
對話框的程式部分

備註：[補充資料]
目前讀過的程式書籍:
Clean Code 無瑕的程式碼:敏捷軟體開發技巧守則
Kent Beck的實作模式
深入淺出物件導向分析與設計
設計模式與遊戲開發的完美結合
程式設計師從零開始邁向架構師之路
UML物件導向系統分析與設計（第四版）
單元測試的藝術
重構:感善既有程式的設計
依賴注入：原理、實作與設計模式
打造可維護軟體：編寫可維護程式碼的10項法則 (C#版)
無瑕的程式碼 番外篇：專業程式設計師的生存之道
人月神話：軟體專案管理之道
之後要看的:
More effective c#
CLR via C#
我只是想知道我目前還缺少甚麼寫遊戲程式必要的程式知識，有沒有推薦的書單或網站可以學

*專案或有能力要求，或需要回答考卷為進行職位能力評等，以確保相關人才就位和避免耽誤開發流程

.
.
.

程式：

1. 程式語言：
C#、Java、C++、Kotlin
2. 曾使用的遊戲引掣：
Unity、RPG Maker XP
3. 曾參與開發的專案、參與人數及開發所需時間#：
SimplyShootingGame是大學跟同學做的作品、3人、1~2星期
FGJ2021是我參加今年Faust game jam的專案，6人、2天

4. 自評：
#請標明有沒有發佈及按專案列出各項
SimplyShootingGame
是否有發布:有，在上面
這是我高中時期的射擊遊戲重新修改，也是我學測之後算是恢復程式感覺的作品，以當時的我來說是覺得自己在程式函式庫跟程式語法的使用有比高中熟悉，但也意識到以這種有一堆重複程式碼的寫法寫下去自己早晚會瘋掉，開始以這個方向去尋找程式書籍

FGJ2021
是否有發布:有，在上面
這時我從Unreal的對話框程式再做一些功能增加的作品，因為我第一次跟別人協作Unity，算是在很多地方都大開我的眼界，也認識了一些人，還有跟這次組隊的人在活動結束有在一起做遊戲，雖然兩天的時限讓我覺得壓力挺大的，不過整體收穫很多，也很開心，蠻期待年底的GGJ

（接考卷）
這是要我評論自己這次考試的專案跟題目嗎?我覺得自已有把考試要求的功能做出來，但有幾點我真的需要一點時間去知道發生什麼事/修改
1.因為我用了Unity的New InputSystem，我可能對InputValue的Vector3的數值變化有點誤會，我在取得Input的Vector3時值的反應速度比我想像的慢，之後我要看看是怎麼回事
2.其實我存檔原本想用XML，但我到這次使用才發現原來XML是無法序列化Unity物件的，還有我不知道為什麼要獲取SaveDataFile的檔案時(已經移除Unity物件)會跳出錯誤訊息，我應該要去查發生什麼事，但我已經做到有點累了...所以我最後還是用PlayerPrefs來用InventoryItem的物件做RestartGame的設定了
3.InventoryUI在ItemInformationPanel顯現出來後會往上移，應該是因為我沒有設定Rect Transform的關係，不過我對UI設計其實沒太多研究，因為未來目標不是設計UI，只是我開始覺得去學一下UI跟顏色調配也不是不行
4.我其實對物理碰撞還沒有深入研究，最近都在翻設計模式跟重構之類的書籍，對於這方面真的不太行
5.IsItemUpdate這個boolean值應該要提成Visitor模式，這樣InventorySystem跟InventoryUIController的IsItemUpdate判斷才不會很彆扭
6.委託的使用時機/方式要再多研究
7.整體來說還行，但有很多地方需要改進跟研究
8.筆試的部分我很多題都翻了一堆資料才寫出來，我真的在C#跟Unity的基礎知識要再加強

**Comment by jcs090218** [comment]
已發出邀請了, 請察看信箱是否有收到邀請信(垃圾訊息也請一併查看). 

如果**成功**加入, 請把這個issue關閉! 感謝! ❤️
