### ISSUE TITLE
入團申請! 我是綠島

### ISSUE THREAD

**Issue by pine0113** [MatchWorkshop/Join#17]
### 入團申請表

Discord ID: g.i#4638

Git ID: pine0113

入團原因：
台大資工所肄業後當了7年 IT工程師，沒有遊戲開發經驗但對相關領域有興趣，想用業餘時間進行遊戲開發

入團期望：
先通過基本的程式能力後從旁參與專案，從中再了解程式跟企劃的作業流程跟所需技能
希望1年半後湊齊能力可以主持小型遊戲專案

暱稱：綠島

專長*：程式

能參與製作時間：一三五夜間、六日下午到夜間

作品集：無，(本職工作是IT工程師

備註：[補充資料]

程式：

1. 程式語言：php, ruby, C#, shell script

2. 曾使用的遊戲引掣：Unity (學習中)

3. 曾參與開發的專案、參與人數及開發所需時間#：無

4. 自評：
喜愛pixel 風格以及類銀河戰士惡魔城的遊戲，
目前還在進行udemy上的unity遊戲製作課程，
但對一般專案進行的強度跟所需技能不夠清晰，
希望在社群中可以找到更明確的方向

（接考卷）

**Comment by jcs090218** [comment]
已發出邀請了, 請察看信箱是否有收到邀請信(垃圾訊息也請一併查看). 

如果**成功**加入, 請把這個issue關閉! 感謝! ❤️
