### ISSUE TITLE
入團申請! 我是xxx

### ISSUE THREAD

**Issue by aqurius01** [MatchWorkshop/Join#3]
### 入團申請表

Discord ID:

入團原因：

入團期望：

暱稱：

專長*：企劃/美術/程式/音樂/其他

能參與製作時間：

作品集：git/網站連結/作品名稱、擔任職位/參與部份

備註：[補充資料]

*專案或有能力要求，或需要回答考卷為進行職位能力評等，以確保相關人才就位和避免耽誤開發流程

.
.
.

程式：

1. 程式語言：

2. 曾使用的遊戲引掣：

3. 曾參與開發的專案、參與人數及開發所需時間#：

4. 自評：

#請標明有沒有發佈及按專案列出各項

（接考卷）

**Comment by jcs090218** [comment]
新版在 #6.
