### ISSUE TITLE
入團申請表

### ISSUE THREAD

**Issue by wayen22884** [MatchWorkshop/Join#8]
Discord ID: wayne22884#0131

**Comment by jcs090218** [comment]
邀請了, 請查收一下你的Email. 你的專案為No. 17! 👍🏻

**Comment by Evemio** [comment]
Discord ID :EveClaire#2198

**Comment by jcs090218** [comment]
@Evemio 我有發你Email囉! 請到Email查收並點開加入連結! 👍

**Comment by Kowayuwu** [comment]
Discord ID: koway#9976
