### ISSUE TITLE
入團申請! 我是阿半

### ISSUE THREAD

**Issue by lynn40725** [MatchWorkshop/Join#9]
### 入團申請表

Discord ID:lynn40725

Git ID:lynn40725

入團原因：已經在裡面

入團期望：製作出有趣的遊戲

暱稱：阿半

專長*：企劃/其他：通靈

能參與製作時間：少

作品集：https://wall.gamer.com.tw/redir.php?userId=lynn40725

備註：[補充資料]

*專案或有能力要求，或需要回答考卷為進行職位能力評等，以確保相關人才就位和避免耽誤開發流程

.
.
.

程式：

1. 程式語言：

2. 曾使用的遊戲引掣：RM VA, MV, Unity, Ren’Py, 吉里吉里

3. 曾參與開發的專案、參與人數及開發所需時間#：

4. 自評：

#請標明有沒有發佈及按專案列出各項

（接考卷）

**Comment by jcs090218** [comment]
哈哈 你好, 你也來囉! 😄 

邀請了! 請查收Email! 👍
